### ISSUE TITLE
how can I get wavlist for data preparation?

### ISSUE THREAD

**Issue by SouppuoS** [felixfuyihui/AISHELL-4#4]
Hi Fu, I notice scripts in data preparation have to take several `wavlists` as input, like `spk1_list`, `wav_list`, `noise_list`. 
How can I get or generate these lists? Are there any rules or scripts? Thx!

**Comment by thorui** [comment]
How did you solve this problem?

**Comment by jonathan-tcliu** [comment]
Hi @SouppuoS , I was wondering if you could tell me how you eventually solved this problem?

**Comment by SouppuoS** [comment]
Hi @jonathan-liu-0204  , `wavlists` is set in scp-style.
like:
> filename path-of-file

or
> path-of-file

I'm not sure which one. It was already 2 years ago I run this code.

**Comment by jonathan-tcliu** [comment]
Hi @SouppuoS ,

Ok! Thanks for the support 🙇
