### ISSUE TITLE
something wrong with the pretrained asr model 

### ISSUE THREAD

**Issue by wpupup** [felixfuyihui/AISHELL-4#5]
Hi：
   there is something wrong with the pre-trained asr model, it can't be decompressed, can you fixed this problem ????

**Comment by SouppuoS** [comment]
> Hi：
> there is something wrong with the pre-trained asr model, it can't be decompressed, can you fixed this problem ????

Hi wpupup, I'm working on the baseline too. 
And I found the pretrained asr model (`best.pt.tar`) is NOT compressed. You can just `torch.load` it.

**Comment by wpupup** [comment]
> > Hi：
> > there is something wrong with the pre-trained asr model, it can't be decompressed, can you fixed this problem ????
> 
> Hi wpupup, I'm working on the baseline too.
> And I found the pretrained asr model (`best.pt.tar`) is NOT compressed. You can just `torch.load` it.

。。。 OK，Thank you very much....!!!
