### ISSUE TITLE
How to prepare each .scp file?

### ISSUE THREAD

**Issue by ZeroRin** [felixfuyihui/AISHELL-4#6]
I tried to format all required .scp as <id> <filepath>. It worked for the front-end part, but I encountered some problems when doing ASR and evaluation. I wonder what the exact format of each .scp file is. especially wav_nospk_nofe.scp, wav_spk_nofe.scp, wav_nospk_fe.scp and wav_spk_fe.scp for ASR.
1~2 lines of examples should be very helpful.

**Comment by Alex-Songs** [comment]
Can the author provide a data preparation script? Thanks! @felixfuyihui

**Comment by felixfuyihui** [comment]
> I tried to format all required .scp as . It worked for the front-end part, but I encountered some problems when doing ASR and evaluation. I wonder what the exact format of each .scp file is. especially wav_nospk_nofe.scp, wav_spk_nofe.scp, wav_nospk_fe.scp and wav_spk_fe.scp for ASR. 1~2 lines of examples should be very helpful.

Sorry for sosososo late reply.
scp means:"wavid wavpath".like:
wav1 /home/xxx/xxx/wav1.wav
wav2 /home/xxx/xxx/wav2.wav
wav3 /home/xxx/xxx/wav3.wav
